---
title: "Project Proposal"
author: "Wang Xiaoyuan"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Topic

I would explore the dataset about the Olympic Games. I would identify temporal change in the number of sports and sport events as the development of Olympic Games. I would also track the participation and performance of women, the number of athletes, the number of NOCs and the difficulties to win a gold in each sport event for each Olympic games.

## Data Sources

The data is downloaded from this kaggle linke: https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results. rgriffin created this dataset in May 2018.

## Description of the Data

This is a historical dataset on the modern Olympic Games. It contains all the Games from Athens 1896 to Rio 2016.There are Summer and Winter Games. The Winter and Summer Games were held in the same year up until 1992.After that, they staggered them such that Winter Games occur on a four year cycle starting with 1994, then Summer in 1996, then Winter in 1998, and so on.  

The dataset athlete_events contains 271116 rows and 15 columns. Each row corresponds to an individual athlete competing in an individual Olympic event(athlete-events).  

The columns are:

    ID - Unique number for each athlete
    Name - Athlete's name
    Sex - M or F
    Age - Integer
    Height - In centimeters
    Weight - In kilograms
    Team - Team name
    NOC - National Olympic Committee 3-letter code
    Games - Year and season
    Year - Integer
    Season - Summer or Winter
    City - Host city
    Sport - Sport
    Event - Event
    Medal - Gold, Silver, Bronze, or NA

## Ideas about the figures that you will create to visualize this data:

I would line chart to show the increment of sport events athletes number along the time. I would use scatter plot to show the number of athlete and number of gold medal for each country in each Olympic Games. I would use bar chart to show the top 3 country in gold medal leader board and the gold medal number in each Summer and Winter Games.

